server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Podman container logs (rootless) - This will capture your Go app logs
  - job_name: podman-containers-rootless
    static_configs:
      - targets:
          - localhost
        labels:
          job: podman-containers
          __path__: /home/*/.local/share/containers/storage/overlay-containers/*/userdata/ctr.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            container_name: attrs.name
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Journald logs for system services and containers
  - job_name: journald
    journal:
      json: false
      max_age: 12h
      labels:
        job: journald
    pipeline_stages:
      - json:
          expressions:
            message: MESSAGE
            unit: _SYSTEMD_UNIT
            hostname: _HOSTNAME
            priority: PRIORITY
            container_name: CONTAINER_NAME
      - labels:
          unit:
          hostname:
          priority:
          container_name:

  # System logs (if accessible)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/messages
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+?):\s+(?P<message>.*)$'
      - labels:
          hostname:
          service:
      - timestamp:
          source: timestamp
          format: Jan 2 15:04:05
