version: "3.8"

services:
  # Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Loki
  loki:
    image: grafana/loki:2.9.2
    ports: "3100:3100"
    command: -config.file=/etc/loki/local-config.yml

  # Promtail
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  # Node-Exporter
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
